pipeline {
    agent any

    stages {
        stage(build){
            steps {
                echo "Build ok"
            }
        }

        stage(test){
            steps {
                echo "Test ok"
            }
        }

        stage(deploy){   
            steps {
                echo "Deploiement ok"
            }
        }

    }
}
