pipeline {
    agent any
    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'false'
        GITLAB_CDS = credentials('gitlab')
    }
    stages {
        stage(build){
            steps {
                sh "docker build -t jengit ."
            }
        }

        stage("push to registy"){
            steps {
                withCredentials([usernamePassword(credentialsId:'gitlab',usernameVariable:'username',passwordVariable:'password')]){
                    sh "docker login -u $username -p $password registry.gitlab.com"
                }
                sh "docker tag jengit registry.gitlab.com/testdeploy11/node:stic"
                sh "docker push registry.gitlab.com/testdeploy11/node:stic"
            }
        }

        stage(test){
            steps {
                echo "test"
            }
        }

        stage(deploy){   
            steps {
                sh "ansible-playbook -i ansible/hosts -e 'ansible_password=vagrant' -e registry_user=$GITLAB_CDS_USR -e registry_password=$GITLAB_CDS_PSW -u vagrant ansible/playbook.yml"
            }
        }

    }
}
