- name: deployement with ansible
  hosts: all
  become: yes
  tasks:

    - name: copy compose file
      copy:
        src: ../compose.yml
        dest: /tmp/compose.yml

    - name: Log into DockerHub
      docker_login:
        username: "{{ registry_user }}"
        password: "{{ registry_password }}"
        registry: registry.gitlab.com

    - name: deploy compose file
      shell: 
        cmd: "docker-compose up -d"
        chdir: /tmp
